// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnboardingApi.Persistence.Context;

#nullable disable

namespace OnboardingApi.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240510184714_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnboardingApi.Models.Atividade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlteradoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Classificacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComoFazer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Obrigatório")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("TempoEstimado")
                        .HasColumnType("time");

                    b.Property<DateTime>("UltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("OnboardingApi.Models.AtividadeOboarding", b =>
                {
                    b.Property<Guid>("OnboardingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtividadeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comentário")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusAtividade")
                        .HasColumnType("int");

                    b.HasKey("OnboardingId", "AtividadeId");

                    b.HasIndex("AtividadeId");

                    b.ToTable("AtividadesOnboardings");
                });

            modelBuilder.Entity("OnboardingApi.Models.Onboarding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlteradoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NovoTotverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PadrinhoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StatusOnboarding")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NovoTotverId");

                    b.HasIndex("PadrinhoId");

                    b.ToTable("Onboarding");
                });

            modelBuilder.Entity("OnboardingApi.Models.Totver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlteradoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tribe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsuarioRede")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Totvers");
                });

            modelBuilder.Entity("OnboardingApi.Models.AtividadeOboarding", b =>
                {
                    b.HasOne("OnboardingApi.Models.Atividade", "Atividade")
                        .WithMany("Oboardings")
                        .HasForeignKey("AtividadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnboardingApi.Models.Onboarding", "Onboarding")
                        .WithMany("Atividades")
                        .HasForeignKey("OnboardingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atividade");

                    b.Navigation("Onboarding");
                });

            modelBuilder.Entity("OnboardingApi.Models.Onboarding", b =>
                {
                    b.HasOne("OnboardingApi.Models.Totver", "NovoTotver")
                        .WithMany()
                        .HasForeignKey("NovoTotverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnboardingApi.Models.Totver", "Padrinho")
                        .WithMany()
                        .HasForeignKey("PadrinhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NovoTotver");

                    b.Navigation("Padrinho");
                });

            modelBuilder.Entity("OnboardingApi.Models.Atividade", b =>
                {
                    b.Navigation("Oboardings");
                });

            modelBuilder.Entity("OnboardingApi.Models.Onboarding", b =>
                {
                    b.Navigation("Atividades");
                });
#pragma warning restore 612, 618
        }
    }
}
